[package]
name = "io_tracker"
version = "0.1.0"
authors = ["gatowololo <gatowololo@gmail.com>"]
edition = "2018"

[dependencies]
nix = "0.17"
libc = "0.2"
tracing = "0.1.25"
tracing-subscriber = "0.2"
structopt = "0.2"
byteorder = "1"
seccomp-sys = "0.1.2"
anyhow = "1.0"