[package]
name = "io_tracker"
version = "0.1.0"
authors = ["gatowololo <gatowololo@gmail.com>"]
edition = "2018"

[dependencies]
stdext = "0.2.1"
nix = "0.17"
libc = "0.2"
async-trait = "0.1.21"
single_threaded_runtime = { path = "./single_threaded_runtime/"}

tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"

structopt = "0.2"
byteorder = "1"
env_logger = "0.5"
seccomp-sys = "0.1.2"

anyhow = "1.0"

[build-dependencies]
cc = "1.0"