[package]
name = "partracer"
version = "0.1.0"
authors = ["gatowololo <gatowololo@gmail.com>"]
edition = "2018"

[dependencies]
nix = "0.10"
libc = "0.2"
structopt = "0.2"
byteorder = "1"
log = "0.4"
env_logger = "0.5"
seccomp-sys = "0.1.2"
single_threaded_runtime = {path = "./single_threaded_runtime"}
async-trait = "0.1.21"

[build-dependencies]
cc = "1.0"

# [profile.release]
# debug = true