[package]
name = "partracer"
version = "0.1.0"
authors = ["gatowololo <gatowololo@gmail.com>"]
edition = "2018"

[dependencies]
nix = "0.10"
libc = "0.2"
structopt = "0.2"
byteorder = "1"
generator = "0.6"
log = "0.4"
env_logger = "0.5"
seccomp-sys = "0.1.2"
futures-preview = "0.3.0-alpha"

[build-dependencies]
cc = "1.0"

# [profile.release]
# debug = true