[package]
name = "tracer"
version = "0.1.0"
authors = ["gatowololo <gatowololo@gmail.com>"]
edition = "2018"

[dependencies]
nix = "0.17"
libc = "0.2"
async-trait = "0.1.21"
single_threaded_runtime = { path = "../single_threaded_runtime/"}