[package]
name = "wait_executor"
version = "0.1.0"
authors = ["gatowololo <gatowololo@gmail.com>"]
edition = "2018"

[dependencies]
nix = "0.10"
libc = "0.2"
log = "0.4"

# [profile.release]
# debug = true